const horizontalScrollData = {
  HomeDetails1: {
    title:
      " Starting ₹499 | Gear up for victory, next-level gaming starts here",
    Seemore: "See all offers",
    products: [
      "https://m.media-amazon.com/images/I/61Q1Pa4X4-L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61bFfzSUVSL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81nGpi7MaqL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/51-olSNxjoL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81qBiCSoegL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61j3w3LIHqL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71Jv78rB2pL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/516kq12OmmL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81lrq6YHCJL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81rcx2yWUOL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/41GXbgNwQEL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71d4Z5wr+AL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71PfyTreJIL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71Djwqz0AWL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/617TwQzf+ZL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71Tpv2USovL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71ILbCOwZAL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71VR6c3j2bL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71EAZQiRqzL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61yd7UhrD2L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71tPgqe4c0L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71h4wfu+TiL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71J3Zfu2LGL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71jSR95pnPL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71CrQ6owVgL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61IwZwlTopL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/610od+WLwaL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61G5MtZ3fpL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61Si1h97PBL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/51ge-FQJQYL._AC_SY175_.jpg",
      "https://m.media-amazon.com/images/I/61TZMcZdCUL._AC_SY200_.jpg",
      "https://images-eu.ssl-images-amazon.com/images/I/61TezEHI9dL._AC_UL165_SR165,165_.jpg",
      "https://images-eu.ssl-images-amazon.com/images/I/71cPMlKPk-L._AC_UL165_SR165,165_.jpg",
      "https://images-eu.ssl-images-amazon.com/images/I/61Lfhj2LdxL._AC_UL165_SR165,165_.jpg",
    ],
  },
  HomeDetails2: {
    title: "Min. 40% off | Home & kitchen deals from Amazon Launchpad",
    Seemore: "See all offers",
    products: [
      "https://m.media-amazon.com/images/I/61LyTduKk0L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61+mK08QwBL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/51p4OMG-spL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61yKVTOOgsL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71nI2weowrL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/41ce3W2cEfL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61RRNTbOnVL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71ALUhHMH1L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/51oPtomQYYL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71e+WnY7rML._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/41TXlDE74uL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61Sq+Usu0hL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/51v2BAIVItL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61-7-JQWxAL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81wWS8RqpOL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61WnmpLwAQL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71lXH8K7D9L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/51MctYF8BiL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/51iOIPuNN5L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71mfuZ4R52L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61JjdIoAtgL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71qEqnkZg8L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61mbLfJYofL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61+rWQw-zbL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/51RXzjrUmkL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71zjvUApaRL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61wzo-7firL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71erHCKJ3WL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/715j01W87oL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/51KoFtDZxLL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81KrnHiiIHL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81r6tIbS1cL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61G2USexrDL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71rH4vEE4nL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/716jUnoUA5L._AC_SY200_.jpg",
    ],
  },
  firstDeals: {
    title: "Up to 70% off | Winter essentials curated from emreging brands",
    seeMoreText: "See all deals",
    products: [
      "https://m.media-amazon.com/images/I/619xMvtqClL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81f56tEEbJL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81biKixsaDL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71I53evweVL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81L0Y0-UPGL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/91BGjOT9h0L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71OAvZWN00L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71X+omFHGpL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71DCFWHFolL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71ZxN4i3-oL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/414199djd5L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71gLrwTC-lL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71GaH2nLQ6L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71sB8bOhSmL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81XgZbmqFOL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/713n+TxyfCL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/51sSJUx8mwL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/51Fpt5hLOML._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/81nFk17uzHL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61hz9cK6gnL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61u5oAftaeL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71eUwDk8z+L._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/91hIyGIagmL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/612FuICrCCL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/61MR2yWPQrL._AC_SY200_.jpg",
      "https://m.media-amazon.com/images/I/71xaYhDH9eL._AC_SY200_.jpg",
    ],
  },
};

export default horizontalScrollData;
